services:
  - type: web
    name: ecommerce-customer-analytics
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run 06_streamlit_app.py --server.port $PORT --server.address 0.0.0.0"
    

